# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.37.0"

default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Import app descriptions"
  lane :metadata do
    system './generate_metadata.py'
  end

  desc "Import changelog"
  lane :changelog do
    system './generate_changelog.py'
  end

  desc "Take localized screenshots"
  lane :screenshots do
	screengrab
	system './rename_screenshots.py'
  end

  desc "Deploy a new version to the Google Play (beta track)"
  lane :deploy do
    upload_to_play_store(track: 'beta', apk: 'release/app-release.apk')
  end

  desc "Deploy a new version without screenshots"
  lane :deploy_no_screenshots do
    upload_to_play_store(track: 'beta', apk: 'release/app-release.apk', skip_upload_images:'true', skip_upload_screenshots:'true')
  end
end


# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

# vi:syntax=ruby
